localhost=0,1,2,3,4,5,6,7
deepspeed --master_port=29501 --include=localhost:$localhost train_ds.py \
  --epochs=10 \
  --version=path_to_llava-v1.6-vicuna-7b \
  --dataset_dir='path_to_DRSeg' \
  --dataset="custom_seg" \
  --sample_rates="1"\
  --exp_name="your_exo_name" \
  --val_dataset="custom_seg|val" \
  --train_mask_decoder \
  --vision-tower='path_to_clip-vit-large-patch14' \
  --seg_token_num=3 \
  --num_classes_per_question=3 \
  --batch_size=2 \
  --preprocessor_config='path_to_preprocessor_448.json' \
  --resize_vision_tower \
  --resize_vision_tower_size=448 \
  --vision_tower_for_mask \
  --use_expand_question_list \
  --image_feature_scale_num=2 \
  --separate_mm_projector \
  --conv_type="llava_v1" \
  --is_multipath_encoder 